### ISSUE TITLE
ApexDeployAllDestructive fails with missing argument to tooling-force.com

### ISSUE THREAD

**Issue by thomasdziedzic** [neowit/vim-force.com#49]
```
[ERROR] Executor - specificTypes is required
Exception in thread "main" com.neowit.utils.MissingRequiredConfigParameterException: specificTypes is required
        at com.neowit.utils.BasicConfig.getRequiredProperty(Config.scala:160)
        at com.neowit.utils.Config.getRequiredProperty(Config.scala:203)
        at com.neowit.apex.actions.BulkRetrieve.getSpecificTypesFile(RetrieveMetadata.scala:486)
        at com.neowit.apex.actions.DiffWithRemote$$anon$1.getSpecificTypesFile(RetrieveMetadata.scala:718)
        at com.neowit.apex.actions.BulkRetrieve.doRetrieve(RetrieveMetadata.scala:515)
        at com.neowit.apex.actions.DiffWithRemote.getDiffReport(RetrieveMetadata.scala:724)
        at com.neowit.apex.actions.DeployAllDestructive.act(Deploy.scala:626)
        at com.neowit.apex.actions.Action$class.execute(Action.scala:85)
        at com.neowit.apex.actions.AsyncAction.execute(Action.scala:105)
        at com.neowit.apex.Executor.run(Runner.scala:110)
        at com.neowit.apex.Executor.execute(Runner.scala:46)
        at com.neowit.apex.Runner$.main(Runner.scala:30)
        at com.neowit.apex.Runner.main(Runner.scala)
```

using tooling-force.com v0.3.4.1 and latest vim-force.com source code

**Comment by neowit** [comment]
should be fixed in the current version of the plugin.
If anything does not work after you've checked out latest vim plugin then you may want to update to [tooling-force.com v0.3.4.2](https://github.com/neowit/tooling-force.com/releases/tag/v0.3.4.2). I can not remember if current version of vim plugin depend on that or not.  

Note - tooling-force.com v0.3.4.2 has gone through some massive internal changes and there may be bugs not present in v0.3.4.1

**Comment by thomasdziedzic** [comment]
Thanks, updating vim force.com from git and then using tooling-force.com v0.3.4.2 fixed this issue!
