### ISSUE TITLE
can not run test for specific method

### ISSUE THREAD

**Issue by vitaly-zdanevich** [neowit/vim-force.com#83]
`:ApexTest tooling-sync PluginTest` is ok but

`:ApexTest tooling-sync PluginTest MyMethodName` return

```
 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
 	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
 
 RESULT=FAILURE
 MESSAGE: {"id":5,"text":"/Users/admin/.vim/vim-force-settings/apex_properties_folder/MyMethodName.properties (No such file or directory)","type":"ERROR"}
```

**Comment by neowit** [comment]
you are not using correct syntax to specify test with a single method.
As documented in `:help ApexTest` it has to be in format: 
```
:ApexTest tooling-sync MyTestClassName.MyTestMethodName
``` 
- note the `.` between class and method name.

**Comment by vitaly-zdanevich** [comment]
Oh, sorry again, I found this in documentation - but not in the section `Param 3` but `Param 2` about classes.
